quiver/urls.py
from django.urls import path

from quiver import views

app_name = 'quiver'

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('book_detail/<uuid>', views.book_detail, name='book_detail'),
    path('note_detail/<uuid>', views.note_detail, name='note_detail'),
]

quiver_demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiver/', include('quiver.urls')),
    path('', include('quiver.urls')),
]

quiver/models.py
# Create your models here.
class QvNoteBook:
    def __init__(self, uuid, name, children, path):
        self.uuid = uuid
        self.name = name
        self.children = children if children else []
        self.path = path
        self.notebooks = []
        self.notes = []
        self.parent = None


class QvNote:
    def __init__(self, uuid, title, created_at, updated_at, tags, path):
        self.uuid = uuid
        self.title = title
        self.created_at = created_at
        self.updated_at = updated_at
        self.tags = tags
        self.path = path
        self.cells = []
        self.book = None


class QvCell:
    def __init__(self, qv_type, language, data):
        self.qv_type = qv_type
        self.language = language
        self.data = data
        self.note = None

quiver/views.py
from django.shortcuts import *

# Create your views here.
from quiver.utils.quiver_helper import *

root = get_root()


def book_list(request):
    title = 'quiver book_list'
    book = root
    return render(request, 'quiver/book_list.html', locals())


def book_detail(request, uuid):
    title = 'quiver book_detail'
    book = get_book_by_uuid(uuid)
    return render(request, 'quiver/book_detail.html', locals())


def note_detail(request, uuid):
    title = 'quiver note_detail'
    note = get_note_by_uuid(uuid)
    return render(request, 'quiver/note_detail.html', locals())

quiver/templates/quiver/book_detail.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block main %}


    <div>
        <a href="javascript:history.back()" class="btn btn-block btn-default">返回</a>
    </div>

    {% include 'quiver/show_book_list.html' %}
    {% include 'quiver/show_note_list.html' %}

{% endblock %}

{% block footer %}
{% endblock %}

quiver/templates/quiver/book_list.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block main %}
    {% include 'quiver/show_book_list.html' %}
{% endblock %}

{% block footer %}
{% endblock %}

quiver/templates/quiver/note_detail.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block main %}

    <div>
        <a href="{% url 'quiver:book_detail' note.book.uuid %}" class="btn btn-default btn-block">上一级</a>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>{{ note.title }}</h3>
        </div>
        <div class="panel-body">
            {% for cell in note.cells %}
                <p>
                    {% autoescape off %}
                        {{ cell.data }}
                    {% endautoescape %}
                </p>
            {% endfor %}

        </div>
        <div class="panel-footer"></div>
    </div>

{% endblock %}

{% block footer %}
{% endblock %}

quiver/templates/quiver/show_book_list.html
{% if book.notebooks %}
    <h3 class="page-header">笔记本</h3>
{% endif %}

<ul class="list-group">
    {% for notebook in book.notebooks %}
        <li class="list-group-item">
            <a href="{% url 'quiver:book_detail' notebook.uuid %}">
                <span class="text-primary lead">{{ notebook.name }}</span>
                <span class="text-muted">{{ notebook.uuid }}</span>
                <span class="badge">{{ notebook.notebooks|length }}</span>
            </a>
            <span class="badge">{{ notebook.notes|length }}</span>
        </li>
    {% endfor %}
</ul>

quiver/templates/quiver/show_note_list.html
{% if book.notes %}
    <h3 class="page-header">笔记</h3>
{% endif %}

<ul class="list-unstyled list-inline">
    {% for note in book.notes|dictsort:'title' %}
        <li class="well well-sm">
            <a href="{% url 'quiver:note_detail' note.uuid %}">
                <span>{{ note.title }}</span>
            </a>
        </li>
    {% endfor %}
</ul>

quiver/templates/quiver/template.html
{% extends 'layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block header %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block main %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/site.css' %}">
    {% block styles %}{% endblock %}

    <script src="{% static 'scripts/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    {% block scripts %}{% endblock %}

    <!--[if lt IE 9]>
        <script src="{% static 'scripts/html5shiv-3.5.js' %}"></script>
        <script src="{% static 'scripts/respond-1.4.2.js' %}"></script>
    <![endif]-->
</head>
<body class="container-fluid">

{% include 'nav.html' %}

<header>
    {% block header %}{% endblock %}
</header>

<main>
    {% block main %}{% endblock %}
</main>

<footer>
    {% block footer %}{% endblock %}
</footer>

</body>
</html>

templates/nav.html
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">
                <span class="glyphicon glyphicon-home"></span>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'quiver:book_list' %}">首页</a>
                </li>
                <li><a href="">新增笔记</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Dropdown <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="">Action</a></li>
                        <li><a href="">Another action</a></li>
                        <li><a href="">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>

            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <label for="search"></label>
                    <input id="search" type="text" class="form-control" placeholder="请输入要查询的文章">
                </div>
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Dropdown <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="">Action</a></li>
                        <li><a href="">Another action</a></li>
                        <li><a href="">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>